language: node_js
node_js:
- "10"
cache:
  yarn: true
  directories:
  - node_modules
addons:
  sonarcloud:
    organization: xyo-network
install:
- yarn install
script:
- yarn build
- sonar-scanner
deploy:
  provider: script
  skip_cleanup: true
  script:
    echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    yarn publish
  on:
    branch: master