# This is the mapping of environment variables to configuration settings
port: PORT
graphql: GRAPHQL
data: DATA_DIR
nodeName: NODE_NAME
nodeVersion: NODE_VERSION
isPublic: IS_PUBLIC
ipOverride: IP_OVERRIDE
sql:
  host: SQL__HOST
  port: SQL__PORT
  user: SQL__USER
  password: SQL__PASSWORD
  database: SQL__DATABASE
discovery:
  enable: DISCOVERY__ENABLE
  dns: DISCOVERY__DNS
  bootstrapPeers: DISCOVERY__BOOTSTRAP_PEERS # csv-string i.e. 127.0.0.1:8080,127.0.0.1:8081
  defaultPort: DISCOVERY__DEFAULT_PORT
validation:
  checkPartyLengths: VALIDATION__CHECK_PARTY_LENGTHS
  checkIndexExists: VALIDATION__CHECK_INDEX_EXISTS
  checkCountOfSignaturesMatchPublicKeysCount: VALIDATION__CHECK_COUNT_OF_SIGNATURES_MATCH_PUBLIC_KEYS_COUNT
  validateSignatures: VALIDATION__VALIDATE_SIGNATURES
  validateHash: VALIDATION__VALIDATE_HASH