port: 12000
graphQLPort: 12001
about:
  version: 0.1.0
  url: http://127.0.0.1
  address: abc
  ethAddress: def
ipfs:
  host: localhost
  port: '5001'
  protocol: http
stakedConsensus:
  ipfsHash: QmeFQ55jVbtuVoFYXJdZWKoWMjjs9DZ9teCQhrhTLofGP2
  network: kovan
  platform: ethereum
web3:
  host: http://127.0.0.1:7545
ethereumContracts:
  PayOnDelivery:
    address: please substitute :-)
data: ./diviner-db
discovery:
  ip: 127.0.0.1
  port: 11500
  seeds:
    - ip: 127.0.0.1
      port: 11001