ip: 34.206.64.149
p2pPort: 11500
apis:
  - about
  - blockByHash
  - blockList
  - intersections
  - blocksByPublicKey
  - entities
  - transactionList
bootstrapNodes: []
serverPort: 11000
graphqlPort: 11001
data: ./node-data
name: archivist-diviner
archivist:
  sql:
    name: "MySql"
    platform: "sql"
    host: 127.0.0.1
    user: admin
    password: password
    database: Xyo
    port: 3306
diviner:
  ethereum:
    host: 'wss://kovan.infura.io/ws/v3/8f1e6c44394f4366a49095d9cac828e2'
    account:
      salt: cf82e4a9b4187f4e
      address: '0xff710bF860e6D8e4a2b1E2023C1283e890017CDb'
      encryptedKey: >-
        a6a444bab66e1a29a4f3249f2db54543f38dcea3c799a547a8533b13b5da6d4476b41b43ac55bfbc1aaa8fe5363763f791cc90c950794fe9227a5e5dda218c1cd740f119e380ce4ed3ee01389cb77e5b
    contracts:
      XyStakingConsensus:
        ipfsHash: QmQ22mRgJZ22sZBwVAUjXKiFnMQ7VgTXgWQzC1sdeYXXso
        address: '0xE5A849ae2fB5dDd174678897f22AFf9C213380a3'
      XyGovernance:
        ipfsHash: QmYAMuDs83cC7uWq3u28GqcNzdt3CcQG5HWzuHkdGWE1Q4
        address: '0xC22747981aC1181D898832df92c43Ccf005C098B'
      XyBlockProducer:
        ipfsHash: Qmbki7rTkjTBAqwmjkBTTFNxNgvKwUNSiYbtb2QdGtzLXN
        address: '0xA4C8aC0F0A291f6D5176d6A1201D66d6145B96F2'
ipfs:
  host: ipfs.xyo.network
  port: '5002'
  protocol: https 