ip: 0.0.0.0
p2pPort: 11500
apis:
  - about
  - blockByHash
  - blockList
  - intersections
  - blocksByPublicKey
  - entities
bootstrapNodes: []
origins: 1
serverPort: 11000
graphqlPort: 11001
data: ./node-data
name: archivist
archivist:
  repository:
    name: "DynamoDB"
    platform: "dynamo"
diviner: null
ipfs:
  host: ipfs.xyo.network
  port: '5002'
  protocol: https
