ip: 0.0.0.0
p2pPort: 11500
apis:
  - about
  - blockByHash
  - blockList
  - intersections
  - blocksByPublicKey
  - entities
bootstrapNodes: []
serverPort: 11000
graphqlPort: 11001
data: ./node-data
name: home
archivist:
  repository:
    name: "LevelDB"
    platform: "level"
diviner: null
ipfs:
  host: ipfs.xy.company
  port: '5002'
  protocol: https
